DROP TABLE IF EXISTS DOMAINE;
DROP TABLE IF EXISTS CATEGORIEMOTCLEF;
DROP TABLE IF EXISTS MOTCLEF;
DROP TABLE IF EXISTS CRITERE;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS ELECTRONICDOCUMENT;
DROP TABLE IF EXISTS PAPERDOCUMENT;

													/* CREATION DES TABLES */

CREATE TABLE DOMAINE(
	idDomaine INT NULL AUTO_INCREMENT,
	nomDomaine VARCHAR(50),
	PRIMARY KEY (idDomaine)
	);
	
CREATE TABLE CATEGORIEMOTCLEF(
	idCategorieMotClef INT NOT NULL AUTO_INCREMENT,
	nomCategorieMotClef VARCHAR(30),
	PRIMARY KEY (idCategorieMotClef)
	FOREIGN KEY (idCategorieMotClef) REFERENCES DOMAINE(idDomaine)
	);
	
CREATE TABLE VILLE(
	idVille INT NOT NULL AUTO_INCREMENT,
	nomVille VARCHAR(30),
	PRIMARY KEY (idVille)
	);	
	
CREATE TABLE ENTREPRISE(
	idEntreprise INT NOT NULL AUTO_INCREMENT,
	nomEntreprise VARCHAR(30),
	idVille INT NOT NULL,
	PRIMARY KEY (idEntreprise),
	FOREIGN KEY(idVille)
	REFERENCES VILLE(idVille)
	);	

	
CREATE TABLE STAGE(
	idStage INT NOT NULL AUTO_INCREMENT,
	titreStage VARCHAR(60),
	sujetStage TEXT,
	idEntreprise  INT NOT NULL,
	noEtudiant INT NOT NULL,
	retourEntreprise VARCHAR(20),
	PRIMARY KEY (idStage),
	FOREIGN KEY(idEntreprise) REFERENCES ENTREPRISE(idEntreprise),
	FOREIGN KEY(noEtudiant) REFERENCES ETUDIANT(noEtudiant)
	);
	
CREATE TABLE APOUR(
	idStage INT NOT NULL,
	idMotCle INT NOT NULL,
	PRIMARY KEY (idStage, idMotCle),
	FOREIGN KEY(idStage)
	REFERENCES STAGE(idStage),
	FOREIGN KEY(idMotCle)
	REFERENCES MOTSCLES(idMotCle)
	);
	
													/* INSERTION DES ELEMENTS DES TABLES */


INSERT INTO ETUDIANT VALUES(null, "", "", "");
INSERT INTO ETUDIANT VALUES(null, "Gerum", "Maxime", "Licence Pro");

INSERT INTO MOTSCLES VALUES(null, "PHP");
INSERT INTO MOTSCLES VALUES(null, "SQL");
INSERT INTO MOTSCLES VALUES(null, "Javascript");
INSERT INTO MOTSCLES VALUES(null, "HTML/CSS");
INSERT INTO MOTSCLES VALUES(null, "Ajax");
INSERT INTO MOTSCLES VALUES(null, "Java");
INSERT INTO MOTSCLES VALUES(null, "C/C++");
INSERT INTO MOTSCLES VALUES(null, "Python");
INSERT INTO MOTSCLES VALUES(null, "Android");
INSERT INTO MOTSCLES VALUES(null, "iOS");
	
	
INSERT INTO VILLE VALUES(null, "Belfort");
	
INSERT INTO ENTREPRISE VALUES(null, "Alstom", 1	);

INSERT INTO STAGE VALUES(null, "Modification des panneaux d'affichage", "Mise à jour du code permmettant d'afficher les panneaux d'affichage", 1, 1, "");
	
INSERT INTO APOUR VALUES(1, 7);
	








	

	
