DROP TABLE IF EXISTS EST_TAGE;
DROP TABLE IF EXISTS NOTE;
DROP TABLE IF EXISTS MOTCLEF;
DROP TABLE IF EXISTS CATEGORIEMOTCLEF;
DROP TABLE IF EXISTS PAPERDOCUMENT;
DROP TABLE IF EXISTS ELECTRONICDOCUMENT;
DROP TABLE IF EXISTS CRITERE;
DROP TABLE IF EXISTS DOMAINE;
DROP TABLE IF EXISTS DOCUMENT;

													/* CREATION DES TABLES */

CREATE TABLE DOMAINE(
	idDomaine INT NULL AUTO_INCREMENT,
	nomDomaine VARCHAR(50),
	PRIMARY KEY (idDomaine)
	);
	
CREATE TABLE CRITERE(
	idCritere INT NULL AUTO_INCREMENT,
	nomCritere VARCHAR(30),
	idDomaine INT NOT NULL,
	PRIMARY KEY(idCritere),
	FOREIGN KEY(idDomaine) REFERENCES DOMAINE(idDomaine)
	);
	
CREATE TABLE NOTE(
	idNote INT NOT NULL AUTO_INCREMENT,
	etoiles INT,
	idCritere INT NOT NULL,
	PRIMARY KEY(idNote),
	FOREIGN KEY(idCritere) REFERENCES CRITERE(idCritere)
	);
	
	
CREATE TABLE CATEGORIEMOTCLEF(
	idCategorieMotClef INT NOT NULL AUTO_INCREMENT,
	nomCategorieMotClef VARCHAR(30),
	idDomaine INT NOT NULL,
	PRIMARY KEY (idCategorieMotClef),
	FOREIGN KEY (idDomaine) REFERENCES DOMAINE(idDomaine)
	);
	
	
	
CREATE TABLE MOTCLEF(
	idMotClef INT NOT NULL AUTO_INCREMENT,
	libelle VARCHAR(30),
	idCategorieMotClef INT NOT NULL,
	PRIMARY KEY (idMotClef),
	FOREIGN KEY(idCategorieMotClef) REFERENCES CATEGORIEMOTCLEF(idCategorieMotClef)
	);	
	
	
CREATE TABLE DOCUMENT(
	idDocument INT NOT NULL AUTO_INCREMENT,
	titre VARCHAR(30),
	PRIMARY KEY (idDocument)
	);	

	
CREATE TABLE ELECTRONICDOCUMENT(
	idElectronicDocument INT NOT NULL AUTO_INCREMENT,
	link VARCHAR(300),
	idDocument INT NOT NULL,
	PRIMARY KEY (idElectronicDocument),
	FOREIGN KEY(idDocument) REFERENCES DOCUMENT(idDocument)
	);
	
CREATE TABLE PAPERDOCUMENT(
	idPaperDocument INT NOT NULL AUTO_INCREMENT,
	commentaire TEXT,
	idDocument INT NOT NULL,
	PRIMARY KEY (idPaperDocument),
	FOREIGN KEY(idDocument) REFERENCES DOCUMENT(idDocument)
	);
	
CREATE TABLE EST_TAGE(
	idDocument INT NOT NULL,
	idMotClef INT NOT NULL,
	FOREIGN KEY(idDocument) REFERENCES DOCUMENT(idDocument),
	FOREIGN KEY(idMotClef) REFERENCES MOTCLEF(idMotClef)
	);
	
													/* INSERTION DES ELEMENTS DES TABLES */

